### ISSUE TITLE
Measuring Temperature - Lepton

### ISSUE THREAD

**Issue by dr-m-nasr** [cliffordlab/AutoTriage_release#3]
Hello,
Thank you for releasing this, it's brilliant work. I am curious, i didn't see anywhere in the code where you measure the temperature or use the Lepton at all, am i missing it somewhere or is it still not released? thank you!

**Comment by StefanJiang** [comment]
Hi,

In measure.py, it uses Lepton as a usb cam (device=/dev/video1) to take pictures (using gstreamer) and then it reads in the pictures for temperature. Hope this helps.

**Comment by dr-m-nasr** [comment]
Hello, thats very helpful, thank you.
